version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: test_limin_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=test_limin_marine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 1.1.1.1

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: test_limin_frontend
    restart: always
    ports:
      - "5175:80"
    depends_on:
      - backend
    dns:
      - 8.8.8.8
      - 1.1.1.1